SELECT * FROM department;

SELECT `NAME` FROM `department`;

SELECT * FROM `individual`;

SELECT `FIRST_NAME`, `BIRTH_DATE`FROM `individual`;

SELECT * FROM individual WHERE `FIRST_NAME`= "John";

SELECT * FROM  account;

SELECT * FROM  account WHERE `CUST_ID` = 1 AND `AVAIL_BALANCE` > 1000 ;

SELECT * FROM  account WHERE `CUST_ID` = 3 OR `CUST_ID` = 10 OR `CUST_ID` = 11 ;
SELECT * FROM  `account` WHERE `CUST_ID` IN (3,10,11);
SELECT * FROM  `account` WHERE `AVAIL_BALANCE` BETWEEN 200 AND 1500 ORDER BY `AVAIL_BALANCE`;

SELECT * FROM  `account` WHERE `AVAIL_BALANCE` > 2000 AND `OPEN_EMP_ID` IN (10,16);

sELECT * FROM `account` WHERE (`OPEN_EMP_ID` = 10 OR `OPEN_EMP_ID` = 16) AND `AVAIL_BALANCE` > 2000;

SELECT * FROM `account` WHERE `CUST_ID` = 1 ORDER BY `AVAIL_BALANCE` DESC;

SELECT * FROM `account` ORDER BY `AVAIL_BALANCE` DESC , `OPEN_EMP_ID` DESC;

SELECT DISTINCT `CUST_ID` FROM `account`;
SELECT DISTINCT `CUST_ID` FROM `account` WHERE `AVAIL_BALANCE` > 20000 ORDER BY `CUST_ID` DESC;

SELECT * FROM `account` LIMIT 5,7;

SELECT * FROM `account` LIMIT 7 OFFSET 5;

SELECT * FROM `individual`;
SELECT * FROM `individual` WHERE `FIRST_NAME` LIKE '%j%';